# Generated by Django 4.2.7 on 2026-04-17 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    # This migration was split into two (0003_produto_image and
    # 0004_alter_produto_msgpromocao). Keep a noop migration here so
    # Django won't try to re-apply the same operations and to preserve
    # historical filenames.
    dependencies = [
        ('loja', '0004_usuario'),
    ]

    operations = []
